// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
//
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 /// <summary>
/// Copyright (C) 2015-2018 Regents of the University of California.
/// </summary>
///
namespace net.named_data.jndn.security {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using net.named_data.jndn;
	
	public class RsaKeyParams : KeyParams {
		public RsaKeyParams(Name.Component keyId, int size) : base(getType(), keyId) {
			size_ = size;
		}
	
		public RsaKeyParams(Name.Component keyId) : base(getType(), keyId) {
			size_ = getDefaultSize();
		}
	
		public RsaKeyParams(int size, KeyIdType keyIdType) : base(getType(), keyIdType) {
			size_ = size;
		}
	
		public RsaKeyParams(int size) : base(getType(), net.named_data.jndn.security.KeyIdType.RANDOM) {
			size_ = size;
		}
	
		public RsaKeyParams() : base(getType(), net.named_data.jndn.security.KeyIdType.RANDOM) {
			size_ = getDefaultSize();
		}
	
		public int getKeySize() {
			return size_;
		}
	
		public static int getDefaultSize() {
			return 2048;
		}
	
		public static KeyType getType() {
			return net.named_data.jndn.security.KeyType.RSA;
		}
	
		private readonly int size_;
	}
}
