// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 1/22/16 11:38 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 /// <summary>
/// Copyright (C) 2015-2016 Regents of the University of California.
/// </summary>
///
namespace net.named_data.jndn {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	/// <summary>
	/// A class implements OnInterestCallback if it has onInterest, used to pass a
	/// callback to Face.registerPrefix or Face.setInterestFilter.
	/// </summary>
	///
	public interface OnInterestCallback {
		/// <summary>
		/// When an interest is received which matches the interest filter, onInterest
		/// is called.
		/// </summary>
		///
		/// <param name="prefix">the prefix object - if you need to change it then make a copy.</param>
		/// <param name="interest">The received interest.</param>
		/// <param name="face"></param>
		/// <param name="interestFilterId"></param>
		/// <param name="filter">first argument, prefix, is provided for convenience and is the same as filter.getPrefix(). NOTE: You must not change the filter object - if you need to change it then make a copy.</param>
		void onInterest(Name prefix, Interest interest, Face face,
				long interestFilterId, InterestFilter filter);
	}
}
